### ISSUE TITLE
Openssl Exception during execution

### ISSUE THREAD

**Issue by mariaqur** [smarek/android-unbound-dns#8]
I created package.zip as described in Step-by-Step guide and then followed running guide. I put the package in /data/tmp/local folder of android device using adb push. But when i run "unbound-control-setup" command, i get this exception. 

"generating unbound_server.key
CANNOT LINK EXECUTABLE: cannot locate symbol "signal" referenced by "openssl"...
/data/local/tmp/package/bin/unbound-control-setup fatal error: could not genrsa"

I also tried using it with android code and installed apk in the rooted device. But it gives same exception.

Please let me know how can we resolve this issue.  Thanks 

ENV  is attached

![image](https://cloud.githubusercontent.com/assets/16101129/11502275/0de15f0c-983a-11e5-8391-c04cbbd69086.png)

**Comment by mariaqur** [comment]
The problem is with NDK build. The package was created using 64 bit but I was using 32 bit device. The package recreation worked fine.

**Comment by smarek** [comment]
Cool to know, thanks !

**Comment by smarek** [comment]
Maybe we could add param to enforce 32bit binaries, however now there are no variants made currently (ie. compile for arm6 arm7 x86 x86_64)
